package bdml.core.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frame.proto

public final class FrameOuterClass {
  private FrameOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FrameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Frame)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 version = 1;</code>
     */
    int getVersion();

    /**
     * <code>repeated bytes encryptedCapability = 2;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getEncryptedCapabilityList();
    /**
     * <code>repeated bytes encryptedCapability = 2;</code>
     */
    int getEncryptedCapabilityCount();
    /**
     * <code>repeated bytes encryptedCapability = 2;</code>
     */
    com.google.protobuf.ByteString getEncryptedCapability(int index);

    /**
     * <code>bytes encryptedPayload = 3;</code>
     */
    com.google.protobuf.ByteString getEncryptedPayload();
  }
  /**
   * Protobuf type {@code Frame}
   */
  public  static final class Frame extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Frame)
      FrameOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Frame.newBuilder() to construct.
    private Frame(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Frame() {
      version_ = 0;
      encryptedCapability_ = java.util.Collections.emptyList();
      encryptedPayload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Frame(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              version_ = input.readUInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                encryptedCapability_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000002;
              }
              encryptedCapability_.add(input.readBytes());
              break;
            }
            case 26: {

              encryptedPayload_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          encryptedCapability_ = java.util.Collections.unmodifiableList(encryptedCapability_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FrameOuterClass.internal_static_Frame_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FrameOuterClass.internal_static_Frame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Frame.class, Builder.class);
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>uint32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int ENCRYPTEDCAPABILITY_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> encryptedCapability_;
    /**
     * <code>repeated bytes encryptedCapability = 2;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getEncryptedCapabilityList() {
      return encryptedCapability_;
    }
    /**
     * <code>repeated bytes encryptedCapability = 2;</code>
     */
    public int getEncryptedCapabilityCount() {
      return encryptedCapability_.size();
    }
    /**
     * <code>repeated bytes encryptedCapability = 2;</code>
     */
    public com.google.protobuf.ByteString getEncryptedCapability(int index) {
      return encryptedCapability_.get(index);
    }

    public static final int ENCRYPTEDPAYLOAD_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString encryptedPayload_;
    /**
     * <code>bytes encryptedPayload = 3;</code>
     */
    public com.google.protobuf.ByteString getEncryptedPayload() {
      return encryptedPayload_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (version_ != 0) {
        output.writeUInt32(1, version_);
      }
      for (int i = 0; i < encryptedCapability_.size(); i++) {
        output.writeBytes(2, encryptedCapability_.get(i));
      }
      if (!encryptedPayload_.isEmpty()) {
        output.writeBytes(3, encryptedPayload_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, version_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < encryptedCapability_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(encryptedCapability_.get(i));
        }
        size += dataSize;
        size += 1 * getEncryptedCapabilityList().size();
      }
      if (!encryptedPayload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, encryptedPayload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Frame)) {
        return super.equals(obj);
      }
      Frame other = (Frame) obj;

      boolean result = true;
      result = result && (getVersion()
          == other.getVersion());
      result = result && getEncryptedCapabilityList()
          .equals(other.getEncryptedCapabilityList());
      result = result && getEncryptedPayload()
          .equals(other.getEncryptedPayload());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      if (getEncryptedCapabilityCount() > 0) {
        hash = (37 * hash) + ENCRYPTEDCAPABILITY_FIELD_NUMBER;
        hash = (53 * hash) + getEncryptedCapabilityList().hashCode();
      }
      hash = (37 * hash) + ENCRYPTEDPAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getEncryptedPayload().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Frame parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Frame parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Frame parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Frame parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Frame parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Frame parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Frame parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Frame parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Frame parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Frame parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Frame parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Frame parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Frame prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Frame}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Frame)
        FrameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FrameOuterClass.internal_static_Frame_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FrameOuterClass.internal_static_Frame_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Frame.class, Builder.class);
      }

      // Construct using FrameOuterClass.Frame.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        version_ = 0;

        encryptedCapability_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        encryptedPayload_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FrameOuterClass.internal_static_Frame_descriptor;
      }

      @Override
      public Frame getDefaultInstanceForType() {
        return Frame.getDefaultInstance();
      }

      @Override
      public Frame build() {
        Frame result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Frame buildPartial() {
        Frame result = new Frame(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.version_ = version_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          encryptedCapability_ = java.util.Collections.unmodifiableList(encryptedCapability_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.encryptedCapability_ = encryptedCapability_;
        result.encryptedPayload_ = encryptedPayload_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Frame) {
          return mergeFrom((Frame)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Frame other) {
        if (other == Frame.getDefaultInstance()) return this;
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (!other.encryptedCapability_.isEmpty()) {
          if (encryptedCapability_.isEmpty()) {
            encryptedCapability_ = other.encryptedCapability_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureEncryptedCapabilityIsMutable();
            encryptedCapability_.addAll(other.encryptedCapability_);
          }
          onChanged();
        }
        if (other.getEncryptedPayload() != com.google.protobuf.ByteString.EMPTY) {
          setEncryptedPayload(other.getEncryptedPayload());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Frame parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Frame) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int version_ ;
      /**
       * <code>uint32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>uint32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 version = 1;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> encryptedCapability_ = java.util.Collections.emptyList();
      private void ensureEncryptedCapabilityIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          encryptedCapability_ = new java.util.ArrayList<com.google.protobuf.ByteString>(encryptedCapability_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated bytes encryptedCapability = 2;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getEncryptedCapabilityList() {
        return java.util.Collections.unmodifiableList(encryptedCapability_);
      }
      /**
       * <code>repeated bytes encryptedCapability = 2;</code>
       */
      public int getEncryptedCapabilityCount() {
        return encryptedCapability_.size();
      }
      /**
       * <code>repeated bytes encryptedCapability = 2;</code>
       */
      public com.google.protobuf.ByteString getEncryptedCapability(int index) {
        return encryptedCapability_.get(index);
      }
      /**
       * <code>repeated bytes encryptedCapability = 2;</code>
       */
      public Builder setEncryptedCapability(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEncryptedCapabilityIsMutable();
        encryptedCapability_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes encryptedCapability = 2;</code>
       */
      public Builder addEncryptedCapability(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEncryptedCapabilityIsMutable();
        encryptedCapability_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes encryptedCapability = 2;</code>
       */
      public Builder addAllEncryptedCapability(
          Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureEncryptedCapabilityIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, encryptedCapability_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes encryptedCapability = 2;</code>
       */
      public Builder clearEncryptedCapability() {
        encryptedCapability_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString encryptedPayload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes encryptedPayload = 3;</code>
       */
      public com.google.protobuf.ByteString getEncryptedPayload() {
        return encryptedPayload_;
      }
      /**
       * <code>bytes encryptedPayload = 3;</code>
       */
      public Builder setEncryptedPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        encryptedPayload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes encryptedPayload = 3;</code>
       */
      public Builder clearEncryptedPayload() {
        
        encryptedPayload_ = getDefaultInstance().getEncryptedPayload();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Frame)
    }

    // @@protoc_insertion_point(class_scope:Frame)
    private static final Frame DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Frame();
    }

    public static Frame getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Frame>
        PARSER = new com.google.protobuf.AbstractParser<Frame>() {
      @Override
      public Frame parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Frame(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Frame> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Frame> getParserForType() {
      return PARSER;
    }

    @Override
    public Frame getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Payload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string data = 1;</code>
     */
    String getData();
    /**
     * <code>string data = 1;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <code>repeated bytes attachedCapability = 2;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getAttachedCapabilityList();
    /**
     * <code>repeated bytes attachedCapability = 2;</code>
     */
    int getAttachedCapabilityCount();
    /**
     * <code>repeated bytes attachedCapability = 2;</code>
     */
    com.google.protobuf.ByteString getAttachedCapability(int index);
  }
  /**
   * Protobuf type {@code Payload}
   */
  public  static final class Payload extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Payload)
      PayloadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Payload.newBuilder() to construct.
    private Payload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Payload() {
      data_ = "";
      attachedCapability_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Payload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                attachedCapability_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000002;
              }
              attachedCapability_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          attachedCapability_ = java.util.Collections.unmodifiableList(attachedCapability_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FrameOuterClass.internal_static_Payload_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FrameOuterClass.internal_static_Payload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Payload.class, Builder.class);
    }

    private int bitField0_;
    public static final int DATA_FIELD_NUMBER = 1;
    private volatile Object data_;
    /**
     * <code>string data = 1;</code>
     */
    public String getData() {
      Object ref = data_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>string data = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ATTACHEDCAPABILITY_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> attachedCapability_;
    /**
     * <code>repeated bytes attachedCapability = 2;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getAttachedCapabilityList() {
      return attachedCapability_;
    }
    /**
     * <code>repeated bytes attachedCapability = 2;</code>
     */
    public int getAttachedCapabilityCount() {
      return attachedCapability_.size();
    }
    /**
     * <code>repeated bytes attachedCapability = 2;</code>
     */
    public com.google.protobuf.ByteString getAttachedCapability(int index) {
      return attachedCapability_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, data_);
      }
      for (int i = 0; i < attachedCapability_.size(); i++) {
        output.writeBytes(2, attachedCapability_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, data_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < attachedCapability_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(attachedCapability_.get(i));
        }
        size += dataSize;
        size += 1 * getAttachedCapabilityList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Payload)) {
        return super.equals(obj);
      }
      Payload other = (Payload) obj;

      boolean result = true;
      result = result && getData()
          .equals(other.getData());
      result = result && getAttachedCapabilityList()
          .equals(other.getAttachedCapabilityList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      if (getAttachedCapabilityCount() > 0) {
        hash = (37 * hash) + ATTACHEDCAPABILITY_FIELD_NUMBER;
        hash = (53 * hash) + getAttachedCapabilityList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Payload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Payload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Payload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Payload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Payload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Payload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Payload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Payload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Payload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Payload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Payload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Payload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Payload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Payload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Payload)
        PayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FrameOuterClass.internal_static_Payload_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FrameOuterClass.internal_static_Payload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Payload.class, Builder.class);
      }

      // Construct using FrameOuterClass.Payload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        data_ = "";

        attachedCapability_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FrameOuterClass.internal_static_Payload_descriptor;
      }

      @Override
      public Payload getDefaultInstanceForType() {
        return Payload.getDefaultInstance();
      }

      @Override
      public Payload build() {
        Payload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Payload buildPartial() {
        Payload result = new Payload(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.data_ = data_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          attachedCapability_ = java.util.Collections.unmodifiableList(attachedCapability_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.attachedCapability_ = attachedCapability_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Payload) {
          return mergeFrom((Payload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Payload other) {
        if (other == Payload.getDefaultInstance()) return this;
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        if (!other.attachedCapability_.isEmpty()) {
          if (attachedCapability_.isEmpty()) {
            attachedCapability_ = other.attachedCapability_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureAttachedCapabilityIsMutable();
            attachedCapability_.addAll(other.attachedCapability_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Payload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Payload) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object data_ = "";
      /**
       * <code>string data = 1;</code>
       */
      public String getData() {
        Object ref = data_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string data = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data = 1;</code>
       */
      public Builder setData(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string data = 1;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>string data = 1;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> attachedCapability_ = java.util.Collections.emptyList();
      private void ensureAttachedCapabilityIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          attachedCapability_ = new java.util.ArrayList<com.google.protobuf.ByteString>(attachedCapability_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated bytes attachedCapability = 2;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getAttachedCapabilityList() {
        return java.util.Collections.unmodifiableList(attachedCapability_);
      }
      /**
       * <code>repeated bytes attachedCapability = 2;</code>
       */
      public int getAttachedCapabilityCount() {
        return attachedCapability_.size();
      }
      /**
       * <code>repeated bytes attachedCapability = 2;</code>
       */
      public com.google.protobuf.ByteString getAttachedCapability(int index) {
        return attachedCapability_.get(index);
      }
      /**
       * <code>repeated bytes attachedCapability = 2;</code>
       */
      public Builder setAttachedCapability(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAttachedCapabilityIsMutable();
        attachedCapability_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes attachedCapability = 2;</code>
       */
      public Builder addAttachedCapability(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAttachedCapabilityIsMutable();
        attachedCapability_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes attachedCapability = 2;</code>
       */
      public Builder addAllAttachedCapability(
          Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureAttachedCapabilityIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, attachedCapability_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes attachedCapability = 2;</code>
       */
      public Builder clearAttachedCapability() {
        attachedCapability_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Payload)
    }

    // @@protoc_insertion_point(class_scope:Payload)
    private static final Payload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Payload();
    }

    public static Payload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Payload>
        PARSER = new com.google.protobuf.AbstractParser<Payload>() {
      @Override
      public Payload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Payload(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Payload> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Payload> getParserForType() {
      return PARSER;
    }

    @Override
    public Payload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Frame_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Frame_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Payload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Payload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013frame.proto\"O\n\005Frame\022\017\n\007version\030\001 \001(\r\022" +
      "\033\n\023encryptedCapability\030\002 \003(\014\022\030\n\020encrypte" +
      "dPayload\030\003 \001(\014\"3\n\007Payload\022\014\n\004data\030\001 \001(\t\022" +
      "\032\n\022attachedCapability\030\002 \003(\014b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Frame_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Frame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Frame_descriptor,
        new String[] { "Version", "EncryptedCapability", "EncryptedPayload", });
    internal_static_Payload_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Payload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Payload_descriptor,
        new String[] { "Data", "AttachedCapability", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
